fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Tienda\UserBundle\Entity\User
    registration:
        confirmation:
            enabled: true
    from_email:
        address:        youremailaccount@gmail.com
        sender_name:    YourSenderName
