<?php

namespace AppBundle\Repository;

/**
 * CarritoCopiaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarritoCopiaRepository extends \Doctrine\ORM\EntityRepository
{
    public function queryMoreBuyed()
    {
        return $this->createQueryBuilder('prod')
            ->select('producto.id AS id','COUNT(producto.id) totprod','marcas.nMarca','producto.tipoProducto, producto.modelo','urlImagen.imageName')
            ->groupBy('producto.id')
            ->leftJoin('prod.producto','producto')
            ->leftJoin('producto.marcas','marcas')
            ->leftJoin('producto.urlImagen','urlImagen')
            ->addOrderBy('totprod','DESC')
            ->setMaxResults(1)
            ->getQuery()
            ->execute()
            ;
    }
    
    public function moreBuyed()
    {
        return $this->queryMoreBuyed()->execute();
    }
    
    public function queryAllCompras()
    {
        return $this->createQueryBuilder('c')
            ->select('c.id AS id, c.createdAt', 'producto.ref, producto.tipoProducto, producto.modelo, producto.precio, producto.novedad',
                'marcas.nMarca', 'depts.nombre', 'urlImagen.imageName')
            ->leftJoin('c.producto','producto')
            ->leftJoin('producto.marcas','marcas')
            ->leftJoin('producto.depts','depts')
            ->leftJoin('producto.urlImagen','urlImagen')
            ->addOrderBy('c.createdAt','DESC')
            ->getQuery()
            ->execute()
            ;
    }
    
    public function allCompras()
    {
        return $this->queryAllCompras()->execute();
    }
}
