<?php

namespace AppBundle\Repository;

/**
 * ComentarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComentarioRepository extends \Doctrine\ORM\EntityRepository
{
    public function queryAllComments($id)
    {
        return $this->createQueryBuilder('comment')
            ->select('comment.comentario, comment.createdAt', 'usuario.username')
            ->leftJoin('comment.usuario','usuario')
            ->leftJoin('comment.producto','producto')
            ->andWhere('producto.id = :id')
            ->setParameter('id', $id)
            ->getQuery()
            ->execute()
            ;
    }

    public function allComments($id)
    {
        return $this->queryAllComments($id)->execute();
    }

    public function queryMoreComment()
    {

        return $this->createQueryBuilder('comm')

            ->select('producto.id AS id, producto.tipoProducto, marcas.nMarca, producto.modelo, urlImagen.imageName, COUNT(producto.id) totproducto')
            ->groupBy('producto.id')
            ->leftJoin('comm.producto','producto')
            ->leftJoin('producto.marcas','marcas')
            ->leftJoin('producto.urlImagen','urlImagen')
            //->from('AppBundle:Comentario','a')
            ->addOrderBy('totproducto','DESC') //Muestra 4, 2, 3
            ->setMaxResults(1)

            ->getQuery()
            ->execute()
            ;

    }

    public function moreComment()
    {
        return $this->queryMoreComment()->execute();
    }
}
